service: journal-paper-auto-checker

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'eu-west-1'}
  environment:
    JOURNAL_URL: ${file(./.env.yml):JOURNAL_URL}
    USERNAME: ${file(./.env.yml):USERNAME}
    PASSWORD: ${file(./.env.yml):PASSWORD}
    EMAIL_ADDRESSES: ${file(./.env.yml):EMAIL_ADDRESSES}
    SENDER_EMAIL: ${file(./.env.yml):SENDER_EMAIL}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource:
            - "*"

  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  demo:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: img
