service: journal-checker
frameworkVersion: "3"
package:
  # exclude everything except the code and necesary things:
  exclude:
    - ./**
  include:
    - ./src/**

provider:
  name: aws
  runtime: python3.10
  region: eu-west-1
  environment:
    JOURNAL_URL: ${file(./env.yml):ENV_VARS.JOURNAL_URL}
    USERNAME: ${file(./env.yml):ENV_VARS.USERNAME}
    PASSWORD: ${file(./env.yml):ENV_VARS.PASSWORD}
    EMAIL_ADDRESSES: ${file(./env.yml):ENV_VARS.EMAIL_ADDRESSES}

custom:
  pythonRequirements:
    slim: true
    layer: true

functions:
  cron-checker:
    handler: src/cron_checker.handler
    memorySize: 128
    events:
      - schedule: rate(1 day)
